### ISSUE TITLE
'ngx-uploadcare-widget' is not a known element:

### ISSUE THREAD

**Issue by isnyaga** [uploadcare/ngx-uploadcare-widget#15]
@ZNick1982  I have followed the instructions listed here : [ngx-uploadcare-widget](`https://github.com/uploadcare/ngx-uploadcare-widget`)

in my app.module.ts 

`import { UcWidgetModule } from 'ngx-uploadcare-widget';

@NgModule({
  declarations: [
    AppComponent
],
 imports: [
    BrowserModule,
UcWidgetModule,
],
 ],
  exports: [
    MatTableModule,
    MatPaginatorModule,
    
  ],
  providers: [GlobalService,HerokuService],
  bootstrap: [AppComponent]
})
export class AppModule { }'

I get the following error:

Error: Template parse errors:
'ngx-uploadcare-widget' is not a known element:
1. If 'ngx-uploadcare-widget' is an Angular component, then verify that it is part of this module.
2. If 'ngx-uploadcare-widget' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("ol-12">
      <label class="col-12 control-label no-padding" for="name">Product Image</label>
      [ERROR ->]<ngx-uploadcare-widget crop="9:5" do-not-store='true' images-only="true" public-key="635dd7ed3110dbd3"): ng:///AppModule/BidPageEidtorComponent.html@4:6

**Comment by isnyaga** [comment]
@Chethannp I am not using Ionic but rather pure AngularJs 4

**Comment by Chethannp** [comment]
Yeah but on which pages are you trying to access this module?? because your app.module.ts does not show any other pages which means you are using angular lazy loading. so let says you want to use it in home page then go to home.module.ts and add it like this.

import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { ListPage } from './list';
**import { UcWidgetComponent } from 'ngx-uploadcare-widget';**

@NgModule({
  declarations: [
    ListPage,
  ],
  imports: [
    IonicPageModule.forChild(ListPage),
    UcWidgetComponent 
  ],
})
export class ListPageModule {}


This is what best I can share... :)

**Comment by bautrukevich** [comment]
@isnyaga do you tried? can we close this issue?
